import type { PrimaryForm, Product } from "@/types/product";

/** v0.1 示例商品：覆盖各形态与筛选组合 */
export const PRODUCTS: Product[] = [
  {
    id: "p-001",
    slug: "cowhide-standard-a6-planner",
    name: "牛皮标准款 A6 日程本",
    description: "适合日常日程规划的 A6 定页本，头层牛皮封面。",
    primaryForm: "notebook",
    subcategorySlug: "a6-planner",
    sceneTags: ["daily_journal"],
    audienceTags: ["intermediate"],
    size: "a6",
    material: "leather",
    price: 328,
    compareAtPrice: 368,
    priceBucket: "200_400",
    stockStatus: "in_stock",
    seoTitle: "牛皮标准款 A6 日程本 | Yukiss",
    images: [{ url: "/placeholder-product.svg", alt: "牛皮标准款 A6 日程本" }],
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-05-01T00:00:00.000Z",
  },
  {
    id: "p-002",
    slug: "canvas-a5-grid",
    name: "帆布 A5 方格本",
    description: "轻便帆布封面，方格内页适合笔记与轻微拼贴。",
    primaryForm: "notebook",
    subcategorySlug: "a5-grid",
    sceneTags: ["daily_journal", "creative_sketch"],
    audienceTags: ["beginner"],
    size: "a5",
    material: "canvas",
    price: 168,
    priceBucket: "under_200",
    stockStatus: "in_stock",
    images: [{ url: "/placeholder-product.svg", alt: "帆布 A5 方格本" }],
    createdAt: "2026-01-02T00:00:00.000Z",
    updatedAt: "2026-05-01T00:00:00.000Z",
  },
  {
    id: "p-003",
    slug: "pu-b6-blank",
    name: "PU B6 空白本",
    description: "入门友好，空白内页自由度高。",
    primaryForm: "notebook",
    subcategorySlug: "b6-blank",
    sceneTags: ["creative_sketch", "gift"],
    audienceTags: ["beginner"],
    size: "b6",
    material: "pu",
    price: 98,
    priceBucket: "under_200",
    stockStatus: "low_stock",
    images: [{ url: "/placeholder-product.svg", alt: "PU B6 空白本" }],
    createdAt: "2026-01-03T00:00:00.000Z",
    updatedAt: "2026-05-01T00:00:00.000Z",
  },
  {
    id: "p-004",
    slug: "tn-regular-leather",
    name: "TN 标准尺寸皮套",
    description: "经典旅行者笔记本标准尺寸，可换内芯。",
    primaryForm: "traveler",
    subcategorySlug: "regular",
    sceneTags: ["travel", "daily_journal"],
    audienceTags: ["enthusiast"],
    size: "tn_regular",
    material: "leather",
    price: 458,
    priceBucket: "400_600",
    stockStatus: "in_stock",
    images: [{ url: "/placeholder-product.svg", alt: "TN 标准尺寸皮套" }],
    createdAt: "2026-01-04T00:00:00.000Z",
    updatedAt: "2026-05-01T00:00:00.000Z",
  },
  {
    id: "p-005",
    slug: "tn-passport-canvas",
    name: "TN 护照尺寸帆布套",
    description: "更轻便的护照尺寸，适合随身。",
    primaryForm: "traveler",
    subcategorySlug: "passport",
    sceneTags: ["travel"],
    audienceTags: ["intermediate"],
    size: "tn_passport",
    material: "canvas",
    price: 288,
    priceBucket: "200_400",
    stockStatus: "preorder",
    images: [{ url: "/placeholder-product.svg", alt: "TN 护照尺寸帆布套" }],
    createdAt: "2026-01-05T00:00:00.000Z",
    updatedAt: "2026-05-01T00:00:00.000Z",
  },
  {
    id: "p-006",
    slug: "binder-a5-6ring-fabric",
    name: "布面 A5 六孔活页",
    description: "六孔活页体系，内页可替换。",
    primaryForm: "binder",
    subcategorySlug: "a5-6ring",
    sceneTags: ["daily_journal"],
    audienceTags: ["intermediate"],
    size: "a5",
    material: "fabric",
    price: 268,
    priceBucket: "200_400",
    stockStatus: "in_stock",
    images: [{ url: "/placeholder-product.svg", alt: "布面 A5 六孔活页" }],
    createdAt: "2026-01-06T00:00:00.000Z",
    updatedAt: "2026-05-01T00:00:00.000Z",
  },
  {
    id: "p-007",
    slug: "binder-b5-6ring-pu",
    name: "PU B5 六孔活页",
    description: "更大书写幅面，适合桌面记录。",
    primaryForm: "binder",
    subcategorySlug: "b5-6ring",
    sceneTags: ["creative_sketch"],
    audienceTags: ["beginner"],
    size: "other",
    material: "pu",
    price: 198,
    priceBucket: "200_400",
    stockStatus: "out_of_stock",
    images: [{ url: "/placeholder-product.svg", alt: "PU B5 六孔活页" }],
    createdAt: "2026-01-07T00:00:00.000Z",
    updatedAt: "2026-05-01T00:00:00.000Z",
  },
  {
    id: "p-008",
    slug: "brass-bookmark",
    name: "黄铜书签",
    description: "简约金属书签，不易折损页面。",
    primaryForm: "accessories",
    subcategorySlug: "bookmark",
    sceneTags: ["gift", "daily_journal"],
    audienceTags: ["beginner"],
    size: "other",
    material: "other",
    price: 48,
    priceBucket: "under_200",
    stockStatus: "in_stock",
    images: [{ url: "/placeholder-product.svg", alt: "黄铜书签" }],
    createdAt: "2026-01-08T00:00:00.000Z",
    updatedAt: "2026-05-01T00:00:00.000Z",
  },
  {
    id: "p-009",
    slug: "leather-pen-loop",
    name: "皮革笔夹",
    description: "可夹在书脊或皮套边缘。",
    primaryForm: "accessories",
    subcategorySlug: "pen-loop",
    sceneTags: ["daily_journal", "travel"],
    audienceTags: ["intermediate"],
    size: "other",
    material: "leather",
    price: 38,
    priceBucket: "under_200",
    stockStatus: "in_stock",
    images: [{ url: "/placeholder-product.svg", alt: "皮革笔夹" }],
    createdAt: "2026-01-09T00:00:00.000Z",
    updatedAt: "2026-05-01T00:00:00.000Z",
  },
  {
    id: "p-010",
    slug: "washi-set-botanical",
    name: "植物和纸胶带组",
    description: "三卷入，适合拼贴与分区。",
    primaryForm: "accessories",
    subcategorySlug: "washi",
    sceneTags: ["creative_sketch", "gift"],
    audienceTags: ["beginner"],
    size: "other",
    material: "paper",
    price: 58,
    priceBucket: "under_200",
    stockStatus: "low_stock",
    images: [{ url: "/placeholder-product.svg", alt: "植物和纸胶带组" }],
    createdAt: "2026-01-10T00:00:00.000Z",
    updatedAt: "2026-05-01T00:00:00.000Z",
  },
  {
    id: "p-011",
    slug: "sakura-season-limited",
    name: "春季樱花限定方格本",
    description: "季节限定配色与书边细节。",
    primaryForm: "limited",
    subcategorySlug: "seasonal",
    sceneTags: ["gift", "daily_journal"],
    audienceTags: ["enthusiast"],
    size: "a5",
    material: "fabric",
    price: 228,
    priceBucket: "200_400",
    stockStatus: "in_stock",
    images: [{ url: "/placeholder-product.svg", alt: "春季樱花限定方格本" }],
    createdAt: "2026-01-11T00:00:00.000Z",
    updatedAt: "2026-05-01T00:00:00.000Z",
  },
  {
    id: "p-012",
    slug: "artist-collab-sketch",
    name: "插画师联名速写套装",
    description: "联名封面 + 配套内页，适合涂鸦记录。",
    primaryForm: "limited",
    subcategorySlug: "collab",
    sceneTags: ["creative_sketch", "gift"],
    audienceTags: ["enthusiast"],
    size: "b6",
    material: "pu",
    price: 368,
    priceBucket: "200_400",
    stockStatus: "preorder",
    images: [{ url: "/placeholder-product.svg", alt: "插画师联名速写套装" }],
    createdAt: "2026-01-12T00:00:00.000Z",
    updatedAt: "2026-05-01T00:00:00.000Z",
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return PRODUCTS.find((p) => p.slug === slug);
}

export function filterProducts(
  form?: PrimaryForm,
  subcategorySlug?: string,
): Product[] {
  return PRODUCTS.filter((p) => {
    if (form && p.primaryForm !== form) return false;
    if (subcategorySlug && p.subcategorySlug !== subcategorySlug) return false;
    return true;
  });
}
